name: Deploy NextDNS Config

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: default
    env:
      PROFILE: ${{ secrets.profile }}
      API_KEY: ${{ secrets.api_key }}

    steps:
      - uses: actions/checkout@v4

      - run: ./update-config.sh
